openapi: 3.0.1
info:
  title: Inbound Medic AI API
  description: API for searching and analyzing patient aquisition and medical marketing content from Inbound Medic AI crawled data
  version: '1.0.0'
servers:
  - url: https://ima-api-gpt-plugin.onrender.com/
paths:
  /analyze:
    post:
      operationId: analyzeContent
      summary: Search and analyze patient aquisition and medical marketing content
      description: Search through the patient aquisition and medical marketing content using a query string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: Search query to filter medical content
              required:
                - query
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: string
                    description: Array of matching markdown content
        '500':
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
  /:
    get:
      operationId: getRoot
      summary: Get API information
      description: Returns basic information about the API
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                description: Welcome message 